name: Build Documents

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latex packages
        run: |
          sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y latex-make
          sudo apt-get install -y latex-mk
          sudo apt-get install -y latexmk
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-fonts-recommended
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-lang-german
          sudo apt-get install -y texlive-lang-chinese 
          sudo apt-get install -y texlive-lang-cjk

      - name: Build document
        run: |
          make

      - name: Create Release ${{ github.ref_name }}
        id: create_release
        uses: actions/create-release@v1
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Release Plane9.pdf
        id: upload-release-asset-plane9-pdf 
        uses: actions/upload-release-asset@v1
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Plane9.pdf
          asset_name: Plane9.pdf
          asset_content_type: application/pdf

      - name: Release Players.pdf
        id: upload-release-asset-players-pdf 
        uses: actions/upload-release-asset@v1
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Players.pdf
          asset_name: Players.pdf
          asset_content_type: application/pdf
