name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latex packages
        run: |
          sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
          sudo apt-get install -y latex-make
          sudo apt-get install -y latex-mk
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-fonts-recommended
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-lang-german
          sudo apt-get install -y texlive-lang-chinese 
          sudo apt-get install -y texlive-lang-cjk

        - name: Build document
          run: |
            make
      
#      - uses: xu-cheng/texlive-action/small@v1        
#        with:
#          run: |
#            apk add make
#            make

      - uses: actions/upload-artifact@v3
        with:
          path: |
            Plane9.pdf
            Players.pdf
            Plane9.log
            Players.log
