name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          name: Checkout
      
      - uses: xu-cheng/texlive-action/small@v1        
        with:
          name: Build pdfs
          run: |
            apk add make
            apk add latexmk
            apk add texlive-latex-recommended
            apk add texlive-fonts-recommended
            apk add texlive-latex-extra
            apk add texlive-lang-german
            apk add texlive-lang-chinese
            apk add texlive-lang-cjk
            make

      - uses: actions/upload-artifact@v3
        with:
          name: Release pdfs and logs
          path: |
            Plane9.pdf
            Players.pdf
            Plane9.log
            Players.log
