name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install text packages
        run: sudo apt-get install -y latex-make latex-mk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-lang-german texlive-lang-chinese texlive-lang-cjk
      
      - uses: xu-cheng/texlive-action/small@v1        
        with:
          run: |
            apk add make
            make

      - uses: actions/upload-artifact@v3
        with:
          path: |
            Plane9.pdf
            Players.pdf
            Plane9.log
            Players.log
